version: 2
jobs:
  build:
    working_directory: ~/weather-app
    steps:
      ‐ save_cache:
          key: weather-app-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            ‐ "node_modules"
      ‐ restore_cache:
          key: weather-app-{{ .Branch }}-{{ checksum "package-lock.json" }}
      ‐ run: npm install
      ‐ run: npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI